### PR TITLE
Add API endpoints for CRUD operations on devices

### PR DESCRIPTION
**Pull request by giejay**
Im developing a domoticz plugin for gbridge (https://github.com/giejay/domoticz-gbridge-plugin), which can automically create devices in gBridge based on the description of a device in Domoticz (gBridge:My Light). 

Therefore I need the gBridge to expose some API endpoints so I can fetch current devices, create new devices and delete devices (which are no longer in Domoticz).

Of course, it can also control the devices by subscribing to the MQTT server and turning devices on or off based on the action.

### CODE REVIEW

**Comment by giejay** [comment]
Btw, Im trying to implement Username/Password authentication so the plugin can be used running against gbridge.kappelt.net as well instead of only locally. 

I think I almost figured it out, but it keeps responding:
Incoming message!{'Verb': 'CONNACK', 'Status': 0, 'Description': 'Connection Accepted'}
2018-11-24 05:19:31.664 (gBridge Remote) MqttClient::Subscribe
2018-11-24 05:19:31.715 (gBridge Remote) Message from base
2018-11-24 05:19:31.716 (gBridge Remote) Incoming message!{'Verb': 'SUBACK', 'PacketIdentifier': 1, 'Topics': [{'Description': 'Failure', 'Status': 128}]}

Do you have any idea what the Failure might mean and how to fix it?

Also, when trying it with the sub client, I get no connection at all:
mosquitto_sub --username gbridge-u* --pw my-pass --host mqtt.gbridge.kappelt.net --port 8883 --topic gBridge/u1/d1/onoff -d -v
Client mosqsub/10568-raspberry sending CONNECT
Client mosqsub/10568-raspberry sending CONNECT

Does that last command work for you?

**Comment by giejay** [comment]
Do you think its mergeable already?

**Comment by peterkappelt** [comment]
Looks ok at a first glance.

However, I haven't had enough time to do a full code review yet. I think it'll be done by this weekend.

Is this OK or is it more urgent for you?

**Comment by giejay** [comment]
Thats fine by me, using a modified docker image for now.

**Comment by giejay** [comment]
Btw, Im still trying to get a working mqtt connection to your mqtt server but I cant get it to work, did something change? Im almost positive I had it working 3 weeks back, are you able to connect with the command I posted 4 posts up?

**Pull request merged**
